# Generated by Django 4.2.2 on 2023-07-10 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='phone',
            new_name='Mobile',
        ),
    ]
