# Generated by Django 4.2.2 on 2023-07-10 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_phone_record_mobile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Record',
        ),
    ]
